FROM healthsamurai/devbox:latest

ARG CODA_FHIR_STORE_PORT=${CODA_FHIR_STORE_PORT}
ARG CODA_FHIR_STORE_FHIR_VERSION=${CODA_FHIR_STORE_FHIR_VERSION}

ARG CODA_FHIR_STORE_DB_HOST=${CODA_FHIR_STORE_DB_HOST}
ARG CODA_FHIR_STORE_DB_PORT=${CODA_FHIR_STORE_DB_PORT}
ARG CODA_FHIR_STORE_DB_USERNAME=${CODA_FHIR_STORE_DB_USERNAME}
ARG CODA_FHIR_STORE_DB_PASSWORD=${CODA_FHIR_STORE_DB_PASSWORD}
ARG CODA_FHIR_STORE_DB_NAME=${CODA_FHIR_STORE_DB_NAME}

ARG CODA_FHIR_STORE_LICENSE_ID=${CODA_FHIR_STORE_LICENSE_ID}
ARG CODA_FHIR_STORE_LICENSE_KEY=${CODA_FHIR_STORE_LICENSE_KEY}

ARG CODA_FHIR_STORE_CLIENT_ID=${CODA_FHIR_STORE_CLIENT_ID}
ARG CODA_FHIR_STORE_CLIENT_SECRET=${CODA_FHIR_STORE_CLIENT_SECRET}

ARG CODA_FHIR_STORE_ADMIN_USERNAME=${CODA_FHIR_STORE_ADMIN_USERNAME}
ARG CODA_FHIR_STORE_ADMIN_PASSWORD=${CODA_FHIR_STORE_ADMIN_PASSWORD}

ARG CODA_FHIR_STORE_CLIENT_ID=${CODA_FHIR_STORE_CLIENT_SECRET}
ARG CODA_FHIR_STORE_CLIENT_ID=${CODA_FHIR_STORE_CLIENT_SECRET}
ARG CODA_FHIR_STORE_CLIENT_ID=${CODA_FHIR_STORE_CLIENT_SECRET}

ENV AIDBOX_PORT=${CODA_FHIR_STORE_PORT}
ENV AIDBOX_FHIR_VERSION=${CODA_FHIR_STORE_FHIR_VERSION}

ENV PGHOST=${CODA_FHIR_STORE_DB_HOST}
ENV PGPORT=${CODA_FHIR_STORE_DB_PORT}
ENV PGHOSTPORT=${CODA_FHIR_STORE_PORT}
ENV PGUSER=${CODA_FHIR_STORE_DB_USERNAME}
ENV PGPASSWORD=${CODA_FHIR_STORE_DB_PASSWORD}
ENV PGDATABASE=${CODA_FHIR_STORE_DB_NAME}

ENV AIDBOX_LICENSE_ID=${CODA_FHIR_STORE_LICENSE_ID}
ENV AIDBOX_LICENSE_KEY=${CODA_FHIR_STORE_LICENSE_KEY}
ENV AIDBOX_CLIENT_ID=${CODA_FHIR_STORE_CLIENT_ID}
ENV AIDBOX_CLIENT_SECRET=${CODA_FHIR_STORE_CLIENT_SECRET}
ENV AIDBOX_ADMIN_ID=${CODA_FHIR_STORE_ADMIN_USERNAME}
ENV AIDBOX_ADMIN_PASSWORD=${CODA_FHIR_STORE_ADMIN_PASSWORD}